### ISSUE TITLE
Consider moving all message constants to common enums?

### ISSUE THREAD

**Issue by mikepurvis** [ros/gencpp#25]
Code like this:

```
int foo = <condition> ?
      diagnostic_msgs::DiagnosticStatus::OK :
      diagnostic_msgs::DiagnosticStatus::ERROR;
```

Produces this warning:

```
/home/mpurvis/test_ws/src/test/src/main.cpp: In function ‘int main()’:
/home/mpurvis/test_ws/src/test/src/main.cpp:5:94: warning: enumeral mismatch in conditional expression: ‘diagnostic_msgs::DiagnosticStatus_<std::allocator<void> >::<anonymous enum>’ vs ‘diagnostic_msgs::DiagnosticStatus_<std::allocator<void> >::<anonymous enum>’ [-Wenum-compare]
   int a = false ? diagnostic_msgs::DiagnosticStatus::OK : diagnostic_msgs::DiagnosticStatus::ERROR;
```

Which seems to happen because OK and ERROR come from different anonymous enums. There's a lot of chatter about this warning on the googles:

https://www.google.ca/search?q=Wenum-compare

But it does seem that moving all message constants into a shared enum would provide a simple fix.

**Comment by mikepurvis** [comment]
Trivial reproduction: https://github.com/mikepurvis/gencpp_25

**Comment by efernandez** [comment]
https://github.com/ros/gencpp/blob/indigo-devel/scripts/msg.h.template#L87 does this now:

``` template
@[for constant in spec.constants]@
 @[if (constant.type in ['byte', 'int8', 'int16', 'int32', 'int64', 'char'])]@
   enum { @(constant.name) = @(int(constant.val)) };
 @[elif (constant.type in ['uint8', 'uint16', 'uint32', 'uint64'])]@
   enum { @(constant.name) = @(int(constant.val))u };
 @[else]@
   static const @(gencpp.msg_type_to_cpp(constant.type)) @(constant.name);
 @[end if]@
@[end for]
```

I think this will do it (at least in C99 or C++11, which allows the extra comma on the enum):

``` template
@[for constant in spec.constants]@
   enum {
 @[if (constant.type in ['byte', 'int8', 'int16', 'int32', 'int64', 'char'])]@
     @(constant.name) = @(int(constant.val)),
 @[elif (constant.type in ['uint8', 'uint16', 'uint32', 'uint64'])]@
     @(constant.name) = @(int(constant.val))u,
 @[end if]@
   };
@[end for]

@[for constant in spec.constants]@
 @[if (constant.type not in ['byte', 'int8', 'int16', 'int32', 'int64', 'char', 'uint8', 'uint16', 'uint32', 'uint64'])]@
   static const @(gencpp.msg_type_to_cpp(constant.type)) @(constant.name);
 @[end if]@
@[end for]
```

**Comment by dirk-thomas** [comment]
The warning aims to let you know that the usage might not make sense. In the case of `OK` and `ERROR` it would be reasonable to put them into the same `enum` to avoid the warning.

But what if a message defines two different set of constants: `RESOLUTION1`, `RESOLUTION2`, `FRAMERATE1`, `FRAMERATE2`? In the case of using one resolution constand and one framerate constant the warning would make a lot of sense. Sadly our `.msg` file doesn't provide enough semantic to know which constants to group into a single enum.

So I am not sure if putting all in a single enum is necessarily better. I would look for opinions of other developers (@ros/ros_team) if they think the proposed change should be applied. If the consensus is in favor of this could you please provide a PR implementing it.

Just for the record: I simple workaround to get rid of the warning is obvious to cast each enum to `int`.

**Comment by wjwwood** [comment]
I don't see any problem with moving them into a single anonymous enum. I suppose it might cause issues though. We should make sure to do a relatively deep pre-release with the change.

**Comment by tfoote** [comment]
It is unfortunately information that we cannot capture in the msg format. There are naming heuristics we could implement but I think that is making things more complicated than the benefit would be. 

There are two cases, you either have "one type" of enum or "more than one type" of enum in the message. 

In the first case, relatively common, that it's a single set of values this change makes sense. 

In the latter case the warning is helpful to avoid comparing between types at compile time, typically catching a copy and paste bug. This will manifest as a runtime error when a comparison is made and from the typo you either get a false positive or a false negative. 

We can avoid false positives by using a best practice to keep enum values unique within the message. This will eliminate the chance of false positives.  `if (RESOLUTION1 == FRAMERATE1)` returns true. 

The warning will go away also for false negatives  `if (RESOLUTION1 == FRAMERATE1)` and there's not much we can do for this. 

If in the current state all datatypes are different which means that there is no grouping which means that you would have to cast every instance. This does not improve the type safety since if you cast everything to int by default it might as well not be typed. 

With the scoping within each message at least we will get the type checking between messages. `foo_msg::ERROR` would warn about a comparison to  `bar_msg::OK`. 

So I think moving them to the same enum makes sense.
